version: "3.7"

networks:
  frontend:
  backend:

services:

  order.server:
    container_name: ${MYSQL_SERVER_NAME}
    image: mysql/mysql-server:8.0
    
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./query/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3406:3306"

    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: !!str yes

    env_file:
      - secrets.env
    networks:
      - backend

  tokenserver:
    build:
      context: .\src\Services\TokenServiceApi
      dockerfile: Dockerfile
    image: shoes/token-service
    environment:
      - ASPNETCORE_ENVIRONMENT=ContainerDev
      - MvcClient=http://localhost:5500
      - BasketApiClient=http://localhost:5700
      - OrderApiClient=http://localhost:5800
    container_name: tokenserviceapi
    ports:
      - "5600:80"

    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports: 
      - "1445:1433"

    container_name: mssqlcontainer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ProductApi1!@
    networks:
      - backend
